name: CN2B2T
author: Xzai
version: '${project.version}'
main: cloud.xzai.cn2b2t
description: CN2B2T核心插件
commands:
   test:
      description: 测试指令
      usage: /<command>
      permission: <plugin name>.test
      permission-message: 这是个测试命令,用于插件的开发,你不必执行它
   info:
      description: 查看插件信息的指令
      usage: /<command>